### ISSUE TITLE
Feature request: recognize SQL-style comments

### ISSUE THREAD

**Issue by BrashEQLibrium** [jbryer/sqlutils#3]
I would prefer to be able to continue commenting my SQL code with the -- comment operator. This way I could have my SQL code open in a SQL database for testing, and use it within R via sqlutils. Why would I want to do this? Because SQL database applications are much better at reporting SQL code syntax errors that R and sqlutils. Yet most SQL databases will, of course, fail to recognize the roxygen2-style commenting operator.

For example, if I have a .sql file with -- comments in it, and I execute the query with execQuery, I get this error:

Error in seq_len(ncol(df)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(ncol(df)) : first element used of 'length.out' argument

When I remove the -- comments, there is no such error.

**Comment by BrashEQLibrium** [comment]
Very nice, @Choens ! As I understand it, your editions have been merged with @jbryer's release repository, right?

**Comment by Choens** [comment]
Yes. The two have been merged. At this point sqlutils can handle a double-dash comment line such as:

-- This is a comment
select * from foo;


But it cannot handle the following query:

\* This is a comment *\
select * from foo;

I was going to play around with this over the holidays, but I got sidetracked by family obligations.

--andy

On Sunday, January 04, 2015 05:52:38 PM Ben Hanowell wrote:


Very nice, @Choens[1] ! As I understand it, your editions have been merged with @jbryer[2]'s release repository, right? 
—Reply to this email directly or view it on GitHub[3].[4]



Nullius in verba[5] 

--------
[1] https://github.com/Choens
[2] https://github.com/jbryer
[3] https://github.com/jbryer/sqlutils/issues/3#issuecomment-68660064
[4] https://github.com/notifications/beacon/AAZ8IT5IwqZSi6awlLlGIGeG4iRxUTVpks5neeXmgaJpZM4B9D4h.gif
[5] https://en.wikipedia.org/wiki/Nullius_in_verba
